<a href="https://colab.research.google.com/github/nsk31512/libr_for_ds/blob/homework1/Homework1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

###Задание 1

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 6],
             [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])

In [3]:
mean_a = a.mean(axis=0)
print(mean_a)

[2.  8.4]


###Задание 2


In [4]:
a_centered = a - mean_a
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


###Задание 3

In [5]:
a_centered[0:, 0]

array([-1.,  0.,  1.,  1., -1.])

In [6]:
a_centered[0:, 1]

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [7]:
a_centered_sp = a_centered[0:, 0] @ a_centered[0:, 1]
a_centered_sp

8.0

In [8]:
print(a_centered_sp/4)

2.0


##Задание 4**


In [9]:
a_cov = np.cov(a.T)
a_cov[0, 1]

2.0

#Pandas

###Задание 1

In [10]:
import pandas as pd

In [11]:
authors = pd.DataFrame(
    {
        'author_id': [1, 2, 3],
        'author_name': ['Тургенев', 'Чехов', 'Островский'],
    }
)
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [12]:
book = pd.DataFrame(
    {
       'author_id': [1, 1, 1, 2, 2, 3, 3], 
       'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
       'price': [450, 300, 350, 500, 450, 370, 290],
    }
)
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

##Задание 2

In [13]:
author_price = pd.merge(authors, book, how='outer', on='author_id')
author_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

##Задание 3

In [14]:
top5 = author_price.sort_values('price', ascending = False).head()
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

###Задание 4

In [128]:
author_stat = author_price.drop('book_title', axis = 1)
author_stat = author_stat.drop('author_id', axis = 1)

author_stat_min = author_stat.copy()
author_stat_min['min_price'] = author_stat_min['price']
author_stat_min = author_stat_min.drop('price', axis=1)

author_stat_max = author_stat.copy()
author_stat_max['max_price'] = author_stat_max['price']
author_stat_max = author_stat_max.drop('price', axis=1)


author_stat_mean = author_stat.copy()
author_stat_mean['mean_price'] = author_stat_mean['price']
author_stat_mean = author_stat_mean.drop('price', axis=1)

author_stat_min = author_stat_min.groupby(['author_name']).min()

author_stat_max = author_stat_max.groupby(['author_name']).max()

author_stat_mean = author_stat_mean.groupby(['author_name']).mean()

author_stat = author_stat.drop('price', axis=1)
author_stat = author_stat.drop_duplicates(['author_name'])
author_stat = pd.merge(author_stat, author_stat_min, on='author_name')
author_stat = pd.merge(author_stat, author_stat_max, on='author_name')
author_stat = pd.merge(author_stat, author_stat_mean, on='author_name')
author_stat


author_name  min_price  max_price  mean_price
0    Тургенев        300        450  366.666667
1       Чехов        450        500  475.000000
2  Островский        290        370  330.000000

###Задание 5**

In [137]:
author_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

book_info = pd.pivot_table(author_price, values='price', index=['author_name'], columns=['cover'], aggfunc=np.sum, fill_value=0)
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [138]:
book_info.to_pickle('book_info.pkl')

In [140]:
book_info2 = pd.read_pickle('book_info.pkl')
book_info2

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950