<a href="https://colab.research.google.com/github/nsk31512/libr_for_ds/blob/homework2/Hw2_Repeat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Задания на повторение***

In [61]:
import numpy as np

##1

In [62]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

##2

In [63]:
a1 = a.reshape(6, 2)
a1

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [64]:
a2 = a.reshape(2, 6)
a2

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [65]:
a3 = a.reshape(3, 4)
a3

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [66]:
a4 = a.reshape(4, 3)
a4

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [67]:
a5 = a.T
a5

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

##3

In [68]:
a1 = a.reshape(6, -1)
a1

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [69]:
a2 = a.reshape(3, -1)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [70]:
a3 = a.reshape(4, -1)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [71]:
a4 = a.reshape(-1, 2)
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [72]:
a5 = a.reshape(-1, 6)
a5

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

##4
Массив из одного столбца и 12 строк нельзя назвать одномерным



##5

In [85]:
a = np.zeros([3, 4])
for i in range(len(a)):
  for j in range (len(a[i])):
    a[i][j] = np.random.randn()
a

array([[-1.11188012,  0.31890218,  0.27904129,  1.01051528],
       [-0.58087813, -0.52516981, -0.57138017, -0.92408284],
       [-2.61254901,  0.95036968,  0.81644508, -1.523876  ]])

In [74]:
b = a.flatten()
b

array([ 0.89433233,  0.7549978 , -0.20716589, -0.62347739, -1.50815329,
        1.09964698, -0.17773212, -0.41038331,  1.17971634, -0.89820794,
        0.83479542,  0.29656138])

##6

In [86]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

##7

In [87]:
b = np.arange(20, 1, -2)
b
#разницы между массивами a и b нет

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

##9

In [88]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [78]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [79]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [80]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [81]:
#Матрица B имеет размер 4х4. обратную матрицу вычислить не получится, т.к. матрица В вырожденная.

##10

In [89]:
np.random.seed(42)
a = np.random.rand()
a

0.3745401188473625

##11

In [90]:
c = np.arange(16)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

##12

In [91]:
C = c.reshape(4, 4)
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [93]:
D = B + C*10
D

array([[  5,  24,  43,  62],
       [ 54, 100, 146, 192],
       [103, 176, 249, 322],
       [152, 252, 352, 452]])

In [95]:
det_D = np.linalg.det(D)
det_D

0.0

In [97]:
rank_D = np.linalg.matrix_rank(D)
rank_D

2

In [98]:
D_inv = np.linalg.inv(D)
D_inv

LinAlgError: ignored

Обратной матрицы D не существует, т.к. матрица вырожденная.

##13

Непонятно как решать задачу, учитывая, что обратной матрицы D не существует