<a href="https://colab.research.google.com/github/nsk31512/libr_for_ds/blob/homework2/Hw2_Repeat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Задания на повторение***

In [98]:
import numpy as np
import numpy.matlib

##1

In [99]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

##2

In [100]:
a1 = a.reshape(6, 2)
a1

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [101]:
a2 = a.reshape(2, 6)
a2

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [102]:
a3 = a.reshape(3, 4)
a3

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [103]:
a4 = a.reshape(4, 3)
a4

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [104]:
a5 = a.T
a5

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

##3

In [105]:
a1 = a.reshape(6, -1)
a1

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [106]:
a2 = a.reshape(3, -1)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [107]:
a3 = a.reshape(4, -1)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [108]:
a4 = a.reshape(-1, 2)
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [109]:
a5 = a.reshape(-1, 6)
a5

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

##4
Массив из одного столбца и 12 строк нельзя назвать одномерным



##5

In [110]:
%%time
a = np.zeros([3, 4])
for i in range(len(a)):
  for j in range (len(a[i])):
    a[i][j] = np.random.randn()

CPU times: user 290 µs, sys: 0 ns, total: 290 µs
Wall time: 5.44 ms


In [111]:
%%time
a = np.matlib.randn(3, 4)

CPU times: user 80 µs, sys: 0 ns, total: 80 µs
Wall time: 86.1 µs


In [112]:
%%time
a = np.random.randn(3, 4)

CPU times: user 36 µs, sys: 0 ns, total: 36 µs
Wall time: 40.8 µs


Быстрее всего отработал метод random.randn

In [113]:
a

array([[-0.5336488 , -0.00552786, -0.22945045,  0.38934891],
       [-1.26511911,  1.09199226,  2.77831304,  1.19363972],
       [ 0.21863832,  0.88176104, -1.00908534, -1.58329421]])

In [114]:
b = a.flatten()
b

array([-0.5336488 , -0.00552786, -0.22945045,  0.38934891, -1.26511911,
        1.09199226,  2.77831304,  1.19363972,  0.21863832,  0.88176104,
       -1.00908534, -1.58329421])

##6

In [115]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

##7

In [116]:
b = np.arange(20, 1, -2)
b
#разницы между массивами a и b нет

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

##9

In [117]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [118]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [119]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [120]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [121]:
#Матрица B имеет размер 4х4. обратную матрицу вычислить не получится, т.к. матрица В вырожденная.

##10

In [122]:
np.random.seed(42)
a = np.random.rand()
a

0.3745401188473625

##11

In [123]:
c = np.random.randint(16, size=16)
c

array([12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4,  3,  7])

##12

In [124]:
C = c.reshape(4, 4)
C

array([[12, 14, 10,  7],
       [12,  4,  6,  9],
       [ 2,  6, 10, 10],
       [ 7,  4,  3,  7]])

In [125]:
D = B + C*10
D

array([[125, 154, 123, 102],
       [134,  90, 146, 212],
       [ 43, 146, 249, 312],
       [102, 162, 242, 372]])

In [126]:
det_D = np.linalg.det(D)
det_D

-149097599.9999995

In [127]:
rank_D = np.linalg.matrix_rank(D)
rank_D

4

In [128]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.0004711 ,  0.0111539 , -0.00253901, -0.00435621],
       [ 0.00957225, -0.01715762, -0.00876527,  0.01450486],
       [-0.00167085,  0.01408514,  0.02130578, -0.02543824],
       [-0.00321078, -0.00474937, -0.0093469 ,  0.01411451]])

##13

In [129]:
D_inv = (D_inv <= 0).astype(int)
D_inv

array([[0, 0, 1, 1],
       [0, 1, 1, 0],
       [1, 0, 0, 1],
       [1, 1, 1, 0]])

In [131]:
E = numpy.where(D_inv, B, C)
E

array([[ 12,  14,  23,  32],
       [ 12,  50,  86,   9],
       [ 23,   6,  10, 212],
       [ 32, 122, 212,   7]])

In [132]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [133]:
C

array([[12, 14, 10,  7],
       [12,  4,  6,  9],
       [ 2,  6, 10, 10],
       [ 7,  4,  3,  7]])